# Generated by Django 5.2.11 on 2026-02-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('votes_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VoteBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash', models.CharField(max_length=64)),
                ('voter_id', models.IntegerField()),
                ('candidate_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block_hash', models.CharField(max_length=64)),
            ],
        ),
    ]
