# Generated by Django 5.2.11 on 2026-02-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='candidate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
